{
  "name": "jak-company-test-app",
  "type": "static_site",
  "buildCommand": "echo 'Static site - no build needed'",
  "publishDirectory": ".",
  "staticPublishPath": "./index.html",
  "routes": [
    {
      "source": "/*",
      "destination": "/index.html"
    }
  ],
  "headers": [
    {
      "source": "/*",
      "headers": [
        {
          "key": "X-Content-Type-Options",
          "value": "nosniff"
        },
        {
          "key": "X-Frame-Options",
          "value": "DENY"
        },
        {
          "key": "X-XSS-Protection",
          "value": "1; mode=block"
        }
      ]
    }
  ],
  "env": {
    "NODE_ENV": "production"
  }
}